name: Snake-maker

on:
  schedule:
    - cron: "0 01 * * *"
  workflow_dispatch:

jobs:
  snaker:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Make the moving thing that eats stuff
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      - name: Push the thing to that branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake-ish
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
